config:
  git_provider: github
  model: gpt-4.1
  fallback_models:
    - o4-mini
  publish_output: true
  response_language: en-US
  reasoning_effort: medium

auto_suggestions:
  enabled: true
  mode: diff
  suggestion_type: code
