pr_description:
  publish_description_as_comment: true
  use_bullet_points: true
  enable_pr_type: true

pr_review:
  publish_review_as_comment: true
  enable_inline_comments: true
  enable_summarization: true

config:
  git_provider: github
  model: openrouter/openrouter/openai/gpt-4
  fallback_models:
  - openrouter/openrouter/openai/gpt-3.5-turbo
  publish_output: true
  response_language: en-US
  reasoning_effort: medium
