name: Auto Deploy and Commit

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: Setup Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up

      - name: Configure Git
        run: |
          git config --global user.email "alexey.ovchinnikov.dev@gmail.com"
          git config --global user.name "Ovchinnikov Alexey"

      - name: Update deploy log
        run: echo "Last deployed: $(date)" >> deploy.log

      - name: Commit and push deploy log
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          git add deploy.log
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore: auto update deploy log"
            git push https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:main
          fi
