name: Auto Deploy on changes in main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  auto-commit:
    if: github.actor != 'Hell077'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "alexey.ovchinnikov.dev@gmail.com"
          git config --local user.name "Ovchinnikov Alexey"

      - name: Make changes
        run: |
          echo "Last deployed: $(date)" >> deploy.log

      - name: Commit and push if changes exist
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: auto deploy commit"
            git push
          fi