name: GolangCI Lint

on: [pull_request, push]

jobs:
  golangci-lint:
    name: Lint Go code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run golangci-lint with reviewdog (CLI)
        working-directory: apps/Backend
        run: |
          golangci-lint run --timeout=5m \
          | reviewdog -f=golangci-lint -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
