name: Lint Check

on:
  pull_request:
    branches: [main, develop, feat/**]
  push:
    branches: [main, develop, feat/**]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-go:
    name: 🧼 Golang Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - name: Install golangci-lint and reviewdog
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.55.2
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run golangci-lint with GitHub Checks
        working-directory: apps/Backend
        run: |
          golangci-lint run --out-format=checkstyle \
          | reviewdog -f=checkstyle -reporter=github-check -fail-level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-frontend:
    name: 🎨 ESLint TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: apps/frontend
        run: npm ci

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Run ESLint with GitHub Checks
        working-directory: apps/frontend
        run: |
          npx eslint src --ext .ts,.tsx -f unix \
          | reviewdog -f=eslint -reporter=github-check -fail-level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-style:
    name: 💅 Stylelint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: apps/frontend
        run: npm ci

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Run Stylelint with GitHub Checks
        working-directory: apps/frontend
        run: |
          npx stylelint "**/*.{css,scss}" --formatter unix \
          | reviewdog -f=stylelint -reporter=github-check -fail-level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
