name: Lint Styles (Stylelint)

on: [pull_request, push]

jobs:
  lint-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/frontend
        run: npm ci

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Run Stylelint with ReviewDog
        working-directory: apps/frontend
        run: |
          npx stylelint "**/*.{css,scss}" \
          | reviewdog -f=stylelint -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
