name: GolangCI Lint

on: [pull_request, push]

jobs:
  golangci-lint:
    name: Lint Go code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          golangci_lint_flags: "--timeout=5m"
          fail_on_error: true