name: Update Notion Task Status

on:
  pull_request:
    types: [opened]

jobs:
  move-task:
    runs-on: ubuntu-latest

    steps:
      - name: Update Notion Task by Task ID
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          sudo apt update && sudo apt install -y jq

          echo "🔍 Extracting task ID from PR title..."
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          TASK_ID=$(echo "$PR_TITLE" | grep -o '\[POC-[0-9]\+\]' | tr -d '[]')
          echo "Extracted Task ID: $TASK_ID"

          if [ -z "$TASK_ID" ]; then
            echo "❌ Task ID not found in PR title."
            exit 1
          fi

          echo "🔍 Querying Notion by property 'Task ID'..."
          curl -s -X POST "https://api.notion.com/v1/databases/$DATABASE_ID/query" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            --data "{
              \"filter\": {
                \"property\": \"Task ID\",
                \"rich_text\": {
                  \"equals\": \"$TASK_ID\"
                }
              }
            }" > response.json

          cat response.json

          PAGE_ID=$(jq -r '.results[0].id' response.json)
          echo "Found Page ID: $PAGE_ID"

          if [ "$PAGE_ID" = "null" ] || [ -z "$PAGE_ID" ]; then
            echo "❌ Task not found in Notion by Task ID"
            exit 1
          fi

          echo "✅ Updating status to Ready for review..."
          curl -s -X PATCH "https://api.notion.com/v1/pages/$PAGE_ID" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            --data "{
              \"properties\": {
                \"Status\": {
                  \"multi_select\": [
                    {\"name\": \"Ready for review\"}
                  ]
                }
              }
            }"

          echo "✅ Notion task updated!"
