name: PR Guard

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
      - name: ⛔ Check for required approvals
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.data.number,
            });

            const approved = reviews.data.filter(r => r.state === "APPROVED");
            if (approved.length === 0) {
              core.setFailed("PR must be approved before merging.");
            }
