name: Reject direct push to main

on:
  push:
    branches:
      - main

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: ❌ Fail if pushed directly to main
        run: |
          echo "Direct push to 'main' is not allowed. Use PR!"
          exit 1

